import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// ✅ This is the ONLY place <Navbar /> should be imported and rendered
//    in the entire app — root app/layout.tsx, as a direct child of
//    <body>, a sibling of {children}.
//
// ❌ Do NOT also import/render <Navbar /> inside any page.tsx or any
//    nested layout.tsx (e.g. app/(marketing)/layout.tsx).
//
// ❌ Do NOT wrap {children} — here or in any nested layout/page — in
//    an element that has transform / filter / perspective /
//    will-change / contain / overflow-hidden|auto|scroll. Any of
//    these creates a new CSS containing block, which makes Navbar's
//    `position: fixed` anchor to that wrapper instead of the
//    viewport — that's what caused the cramped/rounded navbar on
//    some pages. (Common culprit: a framer-motion page-transition
//    div with overflow-hidden — keep that wrapper INSIDE {children}
//    content, never around it.)
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        <div className="flex-1">{children}</div>
        <Footer />
      </body>
    </html>
  );
}