/* ============================================================
   BLOG TYPES
============================================================ */

export type BlogSection = {
  heading: string;
  paragraphs: string[];
};

export type BlogService =
  | "digital-software"
  | "enterprise-automation"
  | "global-capability-centers"
  | "ai-voice-call";

export type BlogPost = {
  slug: string;
  title: string;
  category: string;
  service: BlogService;
  lastUpdated: string;
  readTime: string;
  heroImage: string;
  excerpt: string;

  author: {
    name: string;
    role: string;
    photo: string;
    bio: string;
  };

  intro: string[];
  sections: BlogSection[];
};

/* ============================================================
   AUTHOR
============================================================ */

const AUTHOR = {
  name: "Sanjay Salunkhe",

  role:
    "President and Global Head of Digital and Software Services",

  photo:
    "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=300&auto=format&fit=crop",

  bio:
    "Sanjay Salunkhe is the President and Global Head of Digital and Software Services of our Company.",
};

/* ============================================================
   AI-POWERED MEDICAL CODING BLOGS
============================================================ */

export const blogPosts: BlogPost[] = [
  /* ==========================================================
     BLOG 1
  ========================================================== */

  {
    slug:
      "ai-powered-medical-coding-manual-review-to-intelligent-workflows",

    title:
      "AI-Powered Medical Coding: Moving From Manual Review to Intelligent Coding Workflows",

    category:
      "Medical Coding",

    service:
      "enterprise-automation",

    lastUpdated:
      "Sep 7, 2026",

    readTime:
      "7 min read",

    heroImage:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600&auto=format&fit=crop",

    excerpt:
      "Explore how clinical language understanding, AI-assisted recommendations, validation, and human review can reshape medical coding operations without removing professional accountability.",

    author: AUTHOR,

    intro: [
      "Medical coding has traditionally relied on manual review of clinical documentation, with coding professionals reading records line by line to identify relevant diagnoses and procedures.",

      "As documentation volume grows and payer requirements become more complex, purely manual workflows can struggle to keep pace without adding significant headcount.",

      "AI-powered medical coding introduces a structured layer of clinical language understanding and coding recommendations, while keeping qualified professionals in control of every final decision.",
    ],

    sections: [
      {
        heading:
          "1. Where Manual Coding Workflows Run Into Limits",

        paragraphs: [
          "Manual coding depends on individual reviewers reading dense clinical narratives and translating them into structured codes.",

          "This process can be accurate, but it is also time intensive and can vary between reviewers, specialties, and documentation styles.",

          "As volumes increase, manual only workflows can create backlogs that affect claims timelines and downstream revenue cycle operations.",
        ],
      },

      {
        heading:
          "2. What AI Adds to the Coding Process",

        paragraphs: [
          "AI can analyze clinical documentation and surface relevant diagnoses, procedures, and coding relevant context far faster than manual first pass review alone.",

          "Coding recommendations generated by AI are presented with supporting evidence, so reviewers can quickly see why a particular code was suggested.",

          "This does not remove the coding professional from the process. It changes their role from searching documentation to validating and finalizing recommendations.",
        ],
      },

      {
        heading:
          "3. Keeping Human Review at the Center",

        paragraphs: [
          "Coding decisions carry compliance, billing, and clinical accuracy implications, which is why human review remains essential.",

          "AI assisted workflows are designed to route recommendations, exceptions, and low confidence cases to qualified coding professionals for final decisions.",

          "This human in the loop approach preserves accountability while reducing the repetitive portion of coding work.",
        ],
      },

      {
        heading:
          "4. Consistency Across Coders and Specialties",

        paragraphs: [
          "Coding consistency can vary based on individual experience, specialty familiarity, and documentation habits within an organization.",

          "AI assisted coding can apply configured logic and validation checks consistently across cases, which can help reduce variability between reviewers.",

          "This is particularly relevant for organizations that code across multiple specialties or handle high volumes of similar documentation types.",
        ],
      },

      {
        heading:
          "5. Building Toward an Intelligent Coding Operation",

        paragraphs: [
          "Moving from manual to AI assisted coding is typically a phased transition rather than a single switch.",

          "Organizations can start with specific documentation types or specialties, measure accuracy and turnaround improvements, and expand coverage as confidence grows.",

          "Over time, this creates a coding operation where AI handles the repetitive first pass work and professionals focus their expertise on validation, exceptions, and quality.",
        ],
      },
    ],
  },

  /* ==========================================================
     BLOG 2
  ========================================================== */

  {
    slug:
      "human-in-the-loop-ai-healthcare-coding",

    title:
      "Human-in-the-Loop AI for Healthcare Coding",

    category:
      "Medical Coding",

    service:
      "enterprise-automation",

    lastUpdated:
      "Sep 7, 2026",

    readTime:
      "6 min read",

    heroImage:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=1600&auto=format&fit=crop",

    excerpt:
      "Understand why strong healthcare AI workflows combine automation with qualified human review, clear exception handling, and traceable recommendations.",

    author: AUTHOR,

    intro: [
      "Healthcare coding sits at the intersection of clinical accuracy, regulatory compliance, and revenue cycle performance, which is why full automation without oversight is rarely appropriate.",

      "Human-in-the-loop design treats AI as a tool that accelerates and structures the coding process, while qualified professionals remain responsible for final decisions.",

      "This approach can capture the efficiency benefits of AI while preserving the accountability that healthcare coding requires.",
    ],

    sections: [
      {
        heading:
          "1. Why Full Automation Is the Wrong Goal",

        paragraphs: [
          "Coding decisions can affect patient records, compliance standing, and reimbursement, so errors carry real consequences.",

          "Fully automated coding without review introduces risk that most healthcare organizations are not willing to accept.",

          "Human-in-the-loop design instead treats AI as an accelerant for professional judgment rather than a replacement for it.",
        ],
      },

      {
        heading:
          "2. Where AI Adds the Most Value",

        paragraphs: [
          "AI is well suited to repetitive, well defined tasks such as scanning documentation for relevant terms, conditions, and procedures.",

          "It can also apply consistent validation rules across large volumes of cases far faster than manual review alone.",

          "This frees coding professionals to focus on judgment intensive tasks such as ambiguous cases, exceptions, and final sign off.",
        ],
      },

      {
        heading:
          "3. Designing Clear Exception Handling",

        paragraphs: [
          "Not every case will have a clear, high confidence coding recommendation.",

          "Well designed workflows route low confidence, conflicting, or incomplete cases to human reviewers rather than forcing an automated decision.",

          "This exception handling layer is often what determines whether an AI assisted coding program is trusted by coding teams.",
        ],
      },

      {
        heading:
          "4. Traceability and Explainability",

        paragraphs: [
          "Coding professionals need to understand why a recommendation was made in order to trust and efficiently review it.",

          "AI assisted workflows should surface the supporting documentation, terms, and logic behind each recommendation.",

          "This traceability also supports compliance and audit requirements that are common in healthcare coding operations.",
        ],
      },

      {
        heading:
          "5. Measuring the Human-AI Partnership",

        paragraphs: [
          "Success in human-in-the-loop coding should be measured across both AI performance and reviewer experience.",

          "Relevant measures can include recommendation accuracy, review turnaround time, exception rates, and coder feedback.",

          "These measurements help organizations refine the workflow over time rather than treating the initial deployment as a finished state.",
        ],
      },
    ],
  },

  /* ==========================================================
     BLOG 3
  ========================================================== */

  {
    slug:
      "coding-automation-revenue-cycle-performance",

    title:
      "Connecting Coding Automation to Revenue Cycle Performance",

    category:
      "Medical Coding",

    service:
      "enterprise-automation",

    lastUpdated:
      "Sep 7, 2026",

    readTime:
      "6 min read",

    heroImage:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1600&auto=format&fit=crop",

    excerpt:
      "See how coding workflow improvements can support cleaner operational handoffs, reduced rework, and faster downstream processing.",

    author: AUTHOR,

    intro: [
      "Medical coding is one of the earliest steps in the revenue cycle, and issues introduced at this stage can ripple through claims, billing, and collections.",

      "AI assisted coding is not only about coding speed. It can also directly influence how cleanly claims move through downstream revenue cycle processes.",

      "Connecting coding intelligence with revenue cycle operations can help organizations reduce rework and improve overall financial performance.",
    ],

    sections: [
      {
        heading:
          "1. Coding Quality Shapes Claims Outcomes",

        paragraphs: [
          "Coding errors or inconsistencies often surface later as claim denials, delays, or additional review requests from payers.",

          "Improving coding accuracy and consistency at the source can reduce the volume of claims that require rework further down the revenue cycle.",

          "This makes coding quality a meaningful lever for overall revenue cycle performance, not just a documentation exercise.",
        ],
      },

      {
        heading:
          "2. Reducing Turnaround Time Without Sacrificing Accuracy",

        paragraphs: [
          "AI assisted coding can accelerate first pass coding while validation and human review preserve accuracy standards.",

          "Faster, accurate coding can shorten the time between service delivery and claim submission.",

          "This can improve cash flow predictability and reduce the operational burden of managing aging claims.",
        ],
      },

      {
        heading:
          "3. Reducing Avoidable Denials",

        paragraphs: [
          "Some denials are directly tied to coding issues such as missing specificity, mismatched codes, or incomplete documentation support.",

          "Validation rules within an AI assisted coding workflow can flag many of these issues before submission rather than after a denial occurs.",

          "This proactive approach can reduce the volume of appeals and rework that revenue cycle teams need to manage.",
        ],
      },

      {
        heading:
          "4. Creating Visibility Across the Coding to Claims Journey",

        paragraphs: [
          "Connecting coding workflows with claims and revenue cycle systems can create shared visibility into where cases stand.",

          "This visibility can help operations and finance teams understand backlog, turnaround, and exception trends in one place.",

          "Over time, this shared view can support more informed staffing and process decisions.",
        ],
      },

      {
        heading:
          "5. Building a Feedback Loop Between Coding and RCM",

        paragraphs: [
          "Revenue cycle outcomes, such as denial patterns, can provide valuable feedback for refining coding validation rules and workflows.",

          "Organizations can use this feedback to adjust exception handling, documentation guidance, and coding rules over time.",

          "This creates a continuous improvement loop between coding operations and the revenue cycle results they influence.",
        ],
      },
    ],
  },

  /* ==========================================================
     BLOG 4
  ========================================================== */

  {
    slug:
      "medical-coding-quality-ai-assisted-review",

    title:
      "Medical Coding Quality: Improving Accuracy With AI-Assisted Review",

    category:
      "Medical Coding",

    service:
      "enterprise-automation",

    lastUpdated:
      "Sep 7, 2026",

    readTime:
      "6 min read",

    heroImage:
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?q=80&w=1600&auto=format&fit=crop",

    excerpt:
      "Explore how AI-assisted validation, exception handling, and human review can help healthcare coding teams improve consistency and reduce avoidable rework.",

    author: AUTHOR,

    intro: [
      "Coding quality programs traditionally rely on periodic manual audits to identify errors, inconsistencies, and training opportunities.",

      "These audits are valuable, but they typically review a sample of cases after coding has already been completed.",

      "AI-assisted review can extend quality checks closer to the point of coding itself, helping teams catch issues earlier and more consistently.",
    ],

    sections: [
      {
        heading:
          "1. The Limits of Sample Based Audits",

        paragraphs: [
          "Traditional coding audits often review a small percentage of total cases due to the time required for manual review.",

          "This means many potential issues may go unreviewed simply because of audit sample size.",

          "AI-assisted validation can extend consistent checks across a much larger share of coded cases.",
        ],
      },

      {
        heading:
          "2. Applying Validation Rules Consistently",

        paragraphs: [
          "AI can apply configured validation rules, such as flagging missing specificity or conflicting codes, uniformly across cases.",

          "This consistency can reduce the variation that naturally occurs when different reviewers apply judgment differently.",

          "Consistent validation does not replace professional judgment, but it can catch a class of errors before they reach submission.",
        ],
      },

      {
        heading:
          "3. Surfacing Exceptions Earlier",

        paragraphs: [
          "When AI-assisted review flags an exception, it can be routed to a coding professional before the case moves further in the workflow.",

          "This earlier intervention can be more efficient than identifying the same issue during a later audit or after a claim denial.",

          "Over time, tracking common exception types can also highlight documentation or training gaps worth addressing.",
        ],
      },

      {
        heading:
          "4. Supporting Coder Development",

        paragraphs: [
          "Patterns identified through AI-assisted review, such as recurring exception types, can inform targeted coder training and coaching.",

          "This shifts quality management from a purely retrospective activity to one that can also guide ongoing skill development.",

          "Coding teams can use these insights to strengthen consistency across specialties and documentation types.",
        ],
      },

      {
        heading:
          "5. Sustaining Quality as Volume Grows",

        paragraphs: [
          "As coding volumes increase, maintaining consistent quality through manual review alone becomes more difficult.",

          "AI-assisted validation is designed to scale alongside volume without requiring proportional increases in manual audit capacity.",

          "This can help organizations sustain coding quality standards even as documentation volume and complexity grow.",
        ],
      },
    ],
  },

  /* ==========================================================
     BLOG 5
  ========================================================== */

  {
    slug:
      "healthcare-coding-automation-scalable-workflows",

    title:
      "Healthcare Coding Automation: Building Scalable Workflows",

    category:
      "Medical Coding",

    service:
      "enterprise-automation",

    lastUpdated:
      "Sep 7, 2026",

    readTime:
      "6 min read",

    heroImage:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=1600&auto=format&fit=crop",

    excerpt:
      "See how connected coding workflows can scale across specialties while keeping governance, traceability, and professional oversight at the center.",

    author: AUTHOR,

    intro: [
      "Scaling a coding operation usually means handling more documentation, more specialties, or more locations without a proportional increase in coding staff.",

      "AI-powered coding workflows are designed to support this kind of scale, but scaling successfully requires more than adding automation on top of existing processes.",

      "Building scalable coding workflows means thinking about governance, specialty adaptation, and integration from the start.",
    ],

    sections: [
      {
        heading:
          "1. Start With High Volume, Well Defined Use Cases",

        paragraphs: [
          "Scalable coding automation programs typically begin with documentation types and specialties that are high volume and relatively well defined.",

          "Starting narrow allows organizations to validate accuracy and workflow fit before expanding to more complex or lower volume case types.",

          "Early wins in well defined areas also help build organizational confidence in the broader coding automation program.",
        ],
      },

      {
        heading:
          "2. Adapting to Specialty Specific Documentation",

        paragraphs: [
          "Different specialties use different terminology, documentation patterns, and coding requirements.",

          "Scalable workflows need to adapt extraction and recommendation logic to these specialty specific patterns rather than applying a single generic model everywhere.",

          "This adaptation work is often what determines how well an AI assisted coding program performs as it expands beyond its initial use case.",
        ],
      },

      {
        heading:
          "3. Keeping Governance Consistent as Scope Grows",

        paragraphs: [
          "As coding automation expands across specialties and locations, governance standards need to remain consistent.",

          "This includes validation rules, exception handling criteria, review requirements, and audit trail expectations.",

          "Centralized governance helps ensure that scaling automation does not also scale inconsistency or risk.",
        ],
      },

      {
        heading:
          "4. Integrating With Existing Healthcare Systems",

        paragraphs: [
          "Scalable coding workflows need to fit into existing EHR, billing, and revenue cycle systems rather than operating as a disconnected tool.",

          "Integration allows coding intelligence to draw on relevant documentation and pass validated outcomes downstream automatically.",

          "This reduces manual handoffs that can otherwise become a bottleneck as volume increases.",
        ],
      },

      {
        heading:
          "5. Monitoring Performance as the Program Expands",

        paragraphs: [
          "Ongoing monitoring of recommendation accuracy, exception rates, and turnaround time is important as a coding automation program scales.",

          "This monitoring helps organizations identify where performance may be degrading in new specialties or documentation types.",

          "Continuous monitoring, paired with governance and specialty adaptation, is what allows coding automation to scale sustainably over time.",
        ],
      },
    ],
  },
];

/* ============================================================
   GET SINGLE MEDICAL CODING BLOG
============================================================ */

export function getBlogBySlug(
  slug: string
): BlogPost | undefined {
  return blogPosts.find(
    (blog) =>
      blog.slug === slug &&
      blog.service === "enterprise-automation"
  );
}

/* ============================================================
   GET RELATED MEDICAL CODING BLOGS
============================================================ */

export function getRelatedBlogs(
  currentSlug: string,
  count = 3
): BlogPost[] {
  const currentBlog = blogPosts.find(
    (blog) =>
      blog.slug === currentSlug &&
      blog.service === "enterprise-automation"
  );

  if (!currentBlog) {
    return [];
  }

  return blogPosts
    .filter(
      (blog) =>
        blog.slug !== currentSlug &&
        blog.service === "enterprise-automation"
    )
    .slice(0, count);
}